<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AbsenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        DB::table('absensis')->insert([
            //1
            [
                'agenda_id' => 1,
                'user_id' => 1,
                'status' => 'hadir',
                'keterangan' => "Mas'ah ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 1,
                'user_id' => 2,
                'status' => 'hadir',
                'keterangan' => "Indahyani Tawakkal",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 1,
                'user_id' => 3,
                'status' => 'hadir',
                'keterangan' => "Risky Inesa",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 1,
                'user_id' => 4,
                'status' => 'hadir',
                'keterangan' => "Mulyati ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 1,
                'user_id' => 5,
                'status' => 'hadir',
                'keterangan' => "Riska",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 1,
                'user_id' => 6,
                'status' => 'hadir',
                'keterangan' => "Muh. Musyawwir",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 1,
                'user_id' => 7,
                'status' => 'hadir',
                'keterangan' => "St. Nurhalisa, S.Pd",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 1,
                'user_id' => 8,
                'status' => 'hadir',
                'keterangan' => "Sri Sundari Rasyid ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 1,
                'user_id' => 9,
                'status' => 'hadir',
                'keterangan' => "Arifuddin",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 1,
                'user_id' => 10,
                'status' => 'hadir',
                'keterangan' => "Savira D. Salsabella ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 1,
                'user_id' => 11,
                'status' => 'hadir',
                'keterangan' => "Nur Fadilah Putri",
                'created_at' => $now,
                'updated_at' => $now,
            ],

            //2
            [
                'agenda_id' => 2,
                'user_id' => 1,
                'status' => 'hadir',
                'keterangan' => "Mas'ah ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 2,
                'user_id' => 2,
                'status' => 'hadir',
                'keterangan' => "Indahyani Tawakkal",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 2,
                'user_id' => 3,
                'status' => 'hadir',
                'keterangan' => "Risky Inesa",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 2,
                'user_id' => 4,
                'status' => 'hadir',
                'keterangan' => "Mulyati ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 2,
                'user_id' => 5,
                'status' => 'hadir',
                'keterangan' => "Riska",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 2,
                'user_id' => 6,
                'status' => 'hadir',
                'keterangan' => "Muh. Musyawwir",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 2,
                'user_id' => 7,
                'status' => 'hadir',
                'keterangan' => "St. Nurhalisa, S.Pd",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 2,
                'user_id' => 8,
                'status' => 'hadir',
                'keterangan' => "Sri Sundari Rasyid ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 2,
                'user_id' => 9,
                'status' => 'hadir',
                'keterangan' => "Arifuddin",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 2,
                'user_id' => 10,
                'status' => 'hadir',
                'keterangan' => "Savira D. Salsabella ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 2,
                'user_id' => 11,
                'status' => 'hadir',
                'keterangan' => "Nur Fadilah Putri",
                'created_at' => $now,
                'updated_at' => $now,
            ],

            //3
            [
                'agenda_id' => 3,
                'user_id' => 1,
                'status' => 'hadir',
                'keterangan' => "Mas'ah ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 3,
                'user_id' => 2,
                'status' => 'hadir',
                'keterangan' => "Indahyani Tawakkal",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 3,
                'user_id' => 3,
                'status' => 'hadir',
                'keterangan' => "Risky Inesa",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 3,
                'user_id' => 4,
                'status' => 'hadir',
                'keterangan' => "Mulyati ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 3,
                'user_id' => 5,
                'status' => 'hadir',
                'keterangan' => "Riska",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 3,
                'user_id' => 6,
                'status' => 'hadir',
                'keterangan' => "Muh. Musyawwir",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 3,
                'user_id' => 7,
                'status' => 'hadir',
                'keterangan' => "St. Nurhalisa, S.Pd",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 3,
                'user_id' => 8,
                'status' => 'hadir',
                'keterangan' => "Sri Sundari Rasyid ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 3,
                'user_id' => 9,
                'status' => 'hadir',
                'keterangan' => "Arifuddin",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 3,
                'user_id' => 10,
                'status' => 'hadir',
                'keterangan' => "Savira D. Salsabella ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 3,
                'user_id' => 11,
                'status' => 'hadir',
                'keterangan' => "Nur Fadilah Putri",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //4
            [
                'agenda_id' => 4,
                'user_id' => 1,
                'status' => 'hadir',
                'keterangan' => "Mas'ah ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 4,
                'user_id' => 2,
                'status' => 'hadir',
                'keterangan' => "Indahyani Tawakkal",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 4,
                'user_id' => 3,
                'status' => 'hadir',
                'keterangan' => "Risky Inesa",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 4,
                'user_id' => 4,
                'status' => 'hadir',
                'keterangan' => "Mulyati ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 4,
                'user_id' => 5,
                'status' => 'hadir',
                'keterangan' => "Riska",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 4,
                'user_id' => 6,
                'status' => 'hadir',
                'keterangan' => "Muh. Musyawwir",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 4,
                'user_id' => 7,
                'status' => 'hadir',
                'keterangan' => "St. Nurhalisa, S.Pd",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 4,
                'user_id' => 8,
                'status' => 'hadir',
                'keterangan' => "Sri Sundari Rasyid ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 4,
                'user_id' => 9,
                'status' => 'hadir',
                'keterangan' => "Arifuddin",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 4,
                'user_id' => 10,
                'status' => 'hadir',
                'keterangan' => "Savira D. Salsabella ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 4,
                'user_id' => 11,
                'status' => 'hadir',
                'keterangan' => "Nur Fadilah Putri",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            //5
            [
                'agenda_id' => 5,
                'user_id' => 1,
                'status' => 'hadir',
                'keterangan' => "Mas'ah ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 5,
                'user_id' => 2,
                'status' => 'hadir',
                'keterangan' => "Indahyani Tawakkal",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 5,
                'user_id' => 3,
                'status' => 'hadir',
                'keterangan' => "Risky Inesa",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 5,
                'user_id' => 4,
                'status' => 'hadir',
                'keterangan' => "Mulyati ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 5,
                'user_id' => 5,
                'status' => 'hadir',
                'keterangan' => "Riska",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 5,
                'user_id' => 6,
                'status' => 'hadir',
                'keterangan' => "Muh. Musyawwir",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 5,
                'user_id' => 7,
                'status' => 'hadir',
                'keterangan' => "St. Nurhalisa, S.Pd",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'agenda_id' => 5,
                'user_id' => 8,
                'status' => 'hadir',
                'keterangan' => "Sri Sundari Rasyid ",
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
